### ISSUE TITLE
Set the UPDATE's PipelineSize to 1

### ISSUE THREAD

**Issue by g31pranjal** [FoundationDB/fdb-record-layer#2324]
Pipelining the `UPDATE` is not safe in light of Scan Limits which do not get rightly propagated upstream from the `SplitHelper`

**Comment by alecgrieser** [comment]
To add a bit more clarity to this, with a pipeline size > 1, then there can be multiple outstanding record saves. That means:

1. If you terminate an `UPDATE` cursor early, then those updates can still happen in the background. So if you commit that transaction without waiting, then those updates don't happen. This can happen whenever an `UPDATE` cursor is ended early, but it can get particularly problematic if the user has set `failOnScanLimitReached` to `true` and then catches that error, as they have lost the ability to wait for the error.
2. The record saves themselves are happening concurrently, which is problematic because index maintainers are not safe to use concurrently. (See #972.) This can cause problems even if the user waits for the cursor to complete
