### ISSUE TITLE
Update fdb-java to 6.0.15

### ISSUE THREAD

**Issue by ngbinh** [FoundationDB/fdb-record-layer#313]
Currently `fdb-record-layer` seems to depend on older version of `fdb-java` :(

**Comment by alecgrieser** [comment]
Yeah, the `fdb-java` dependency is currently on 5.2.5 and the latest is 6.0.15. A few things of note about that:

1. Even though the bindings are on 5.2, users can still use the Record Layer with 6.0 FDB clusters (by using a 6.0 version of the FDB client library).
1. The FDB Java bindings have a pretty good track record with not breaking backwards compatibility. In particular, a client can safely override the transitive dependency on `fdb-java` to a 6.0 version without breaking things.
1. Because of how the bindings handle versioning, once a user has configured their client with the bindings of a certain version, it is harder to connect to older versions of FDB (but generally not impossible). So if we updated the bindings to 6.0, it would make it harder for users to connect to clusters running FDB 5.2.

All that being said, we probably should update our `fdb-java` version at some point, though there isn’t too much urgency to do so. It does appear that it’s on version 5.2.5 at the moment. We could upgrade to 5.2.8 without any problem, so it’s possible that that should be sooner.

**Comment by ngbinh** [comment]
Good to know, I will try with latest fdb java.Thanks

**Comment by alecgrieser** [comment]
FDB 6.0 has been out for a while; I think it might make sense to upgrade at this point.
