### ISSUE TITLE
Local meta-data has stale version

### ISSUE THREAD

**Issue by Gowri0707** [FoundationDB/fdb-record-layer#843]
Is there any way to overcome local meta-data stale version, when downgrading to previous version.
if so [FDBMetaDataStore](https://github.com/FoundationDB/fdb-record-layer/blob/master/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java) is the solution, then how to achieve it?

**Comment by alecgrieser** [comment]
Hm, I suppose that depends on what the exact circumstances are. In general, it's not safe to actually "roll back" the meta-data (certainly not by using an old version).

Is the concern that you would "bake in" a version of the meta-data into a version of client code, and then be unable to read the database if you needed to revert (let's say for unrelated reasons)? I think, yes, ultimately, the idea would be to initialize an `FDBMetaDataStore` at some keyspace, and then have your application use it to store and retrieve the latest meta-data (rather than baking it into code at all).

How exactly you go about doing that is, frankly, a little under-documented at the moment. At the moment, you'll need to create a new `FDBMetaDataStore` with each transaction and then point it at some key space or subspace. If you then call `.setMetaDataStore(` on an `FDBRecordStoreBuilder`, with a meta-data store created with the same transaction, then it *should* work, though note that it will re-load the full meta-data each time, which can hurt latency and possibly cause a "hot shard" on FDB (if your request rate is high enough).

There is a `MetaDataCache` interface available, though no implementations. See #280.

There's some work trying to improve all of this, and at the very least, we should have more documentation. See #283.

**Comment by alecgrieser** [comment]
I'm going to close this one out for now, but if you have further questions or concerns, feel free to reopen or create a new issue.
