### ISSUE TITLE
AsyncLoadingCache should cancel work on deadline exceeded

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#844]
At the moment, if the `AsyncLoadingCache` starts doing work (including to, say, resolve a key space path element from the directory layer) and it hits a `DeadlineExceededException`, the work isn't cancelled in any way. This means that the work could still be ongoing, even after a caller of the `AsyncLoadingCache` has received an error. This could include doing work touching the database, which can then induce additional load on the system. We should clean up work from that operation.

**Comment by alecgrieser** [comment]
It's also possible that we don't need to special case the deadline exceeded exception.

**Comment by MMcM** [comment]
It's also possible that `AsyncLoadingCache.orElseGet` is just a bad idea, because is introduces real time into the middle of the chained futures. If the extra work that the supplier does to refill the cache is needed, then it contributes to the overall time for the whole chain, which a top-level caller waiting for everything could potentially take into account. As it is, how exactly does failing the whole chain out of the middle help the caller?

**Comment by alecgrieser** [comment]
See also: #853. This doesn't stop using an `AsyncLoadingCache`, though it decreases the likelihood one has placed an infinite loop inside of one, which is nice.

**Comment by alecgrieser** [comment]
Perhaps we will reconsider this at some point, but for the time being, I believe our official advice should be that users should set the transaction's timeout option instead of having work be cancelled by the cache, as that solution seems more robust to more kinds of problems.
