### ISSUE TITLE
Deadline Exceed Error

### ISSUE THREAD

**Issue by laptopisasset** [FoundationDB/fdb-record-layer#856]
Hello,

I am getting deadline exceeded error when trying to insert continously in a remote machine!, If anybody had solved this please let me know!

**Comment by scgray** [comment]
Stack traces are helpful, however this is most likely to issue #853.  If you are using the directory layer (for example, via the `DirectoryLayerDirectory`), the lookups to the directory layer are performed in a second transaction, the results of which are cached.  This lookup is given a certain amount of time to complete (5 seconds), and if that time is exceeded that exception is thrown.  You could be exceeding that time either due to network latencies or due to FDB throttling the GRV's involved in the secondary directory layer transaction.   Issue #853 describes an approach that would allow us to do away with the secondary transaction.   Right now I'm not aware of anyone that is immediately starting on resolving that issue yet (of course, assistance is always welcome!), but if this is happening to excessively high GRV latencies the answer is simply to throttle your work somewhat to give FDB time to catch up.  Alternatively, maybe avoiding the directory layer.

**Comment by laptopisasset** [comment]
Thanks @scgray

**Comment by alecgrieser** [comment]
I'm going to close this one out for now, but if you have further questions or concerns, feel free to reopen or create a new issue.
